apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8084"
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ai-service
