apiVersion: v1
kind: Service
metadata:
  name: github-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: github-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: github-service
