apiVersion: v1
kind: Namespace
metadata:
  name: real-ass
  labels:
    app.kubernetes.io/name: real-ass
    app.kubernetes.io/part-of: real-ass-platform
    app.kubernetes.io/managed-by: kubectl
    environment: production
