import type { VacancyOption } from "./types";

export const VACANCY_OPTIONS: VacancyOption[] = [
  {
    id: "backend-go-platform",
    title: "Backend-инженер (Go, платформа)",
    category: "Backend",
    description: "Микросервисы, API, отказоустойчивость, наблюдаемость, PostgreSQL и Redis.",
    searchTerms: ["бэкенд", "backend", "go", "микросервисы", "апи", "платформа"],
    focusAreas: ["распределенные системы", "надежность", "моделирование данных"],
    primarySkills: ["Go", "PostgreSQL", "Redis", "gRPC", "Docker"],
    theoryFocus: ["компромиссы CAP", "идемпотентность", "согласованность"],
    practiceFocus: ["спроектировать API", "разобрать всплеск задержки", "написать логику повторов"],
  },
  {
    id: "frontend-react-web",
    title: "Frontend-инженер (React, Web)",
    category: "Frontend",
    description: "Сложный UI, состояние приложения, производительность рендера, доступность.",
    searchTerms: ["фронтенд", "frontend", "react", "web", "typescript", "интерфейс"],
    focusAreas: ["управление состоянием", "производительность", "доступность"],
    primarySkills: ["TypeScript", "React", "Vite", "CSS", "Testing Library"],
    theoryFocus: ["жизненный цикл рендера", "доступность", "архитектура состояния"],
    practiceFocus: ["собрать фича-компонент", "исправить лишние перерисовки", "оптимизировать сборку"],
  },
  {
    id: "web-fullstack",
    title: "Web-инженер (Fullstack)",
    category: "Web",
    description: "Сквозные веб-фичи, клиент+сервер, API контракты и качество UX.",
    searchTerms: ["web", "fullstack", "фронтенд", "бэкенд", "node", "веб-разработка"],
    focusAreas: ["контракты API", "веб-производительность", "доставка продукта"],
    primarySkills: ["TypeScript", "HTTP", "SQL", "React", "Node.js"],
    theoryFocus: ["веб-архитектура", "кеширование", "основы безопасности"],
    practiceFocus: ["реализовать endpoint + UI", "профилировать медленную страницу", "исправить race condition"],
  },
  {
    id: "mobile-flutter",
    title: "Mobile-инженер (iOS/Android)",
    category: "Mobile",
    description: "Мобильная архитектура, офлайн-режим, жизненный цикл экранов, crash-free.",
    searchTerms: ["mobile", "ios", "android", "flutter", "kotlin", "swift", "мобильная разработка"],
    focusAreas: ["архитектура приложения", "офлайн-синхронизация", "производительность"],
    primarySkills: ["Kotlin/Swift", "REST", "SQLite", "CI/CD"],
    theoryFocus: ["жизненный цикл мобильного приложения", "восстановление состояния", "энергоэффективность"],
    practiceFocus: ["спроектировать поток синхронизации", "разобрать падение", "реализовать пагинацию"],
  },
  {
    id: "data-engineer",
    title: "Инженер данных",
    category: "Data",
    description: "Пайплайны данных, DWH, качество данных, batch/stream processing.",
    searchTerms: ["data", "etl", "хранилище данных", "spark", "airflow", "инженер данных"],
    focusAreas: ["проектирование пайплайнов", "качество данных", "масштабируемость"],
    primarySkills: ["SQL", "Python", "Airflow", "Kafka", "dbt"],
    theoryFocus: ["моделирование данных", "семантика exactly-once", "происхождение данных"],
    practiceFocus: ["спроектировать ETL", "оптимизировать SQL", "обработать поздние события"],
  },
  {
    id: "ml-engineer",
    title: "ML-инженер (прикладной ИИ)",
    category: "ML",
    description: "Прод ML-системы, мониторинг качества, деградация модели, эксперименты.",
    searchTerms: ["ml", "ai", "машинное обучение", "модель", "вывод"],
    focusAreas: ["сервинг модели", "оценка качества", "мониторинг"],
    primarySkills: ["Python", "PyTorch", "FastAPI", "Feature Store"],
    theoryFocus: ["смещение и разброс", "дрейф", "метрики качества"],
    practiceFocus: ["спроектировать API инференса", "разобрать тревогу о дрейфе", "снизить задержку"],
  },
  {
    id: "devops-sre",
    title: "DevOps / SRE инженер",
    category: "DevOps",
    description: "Надежные релизы, CI/CD, инфраструктура как код, инциденты и SLO.",
    searchTerms: ["devops", "sre", "kubernetes", "terraform", "ci/cd", "дежурство", "инфраструктура"],
    focusAreas: ["реакция на инциденты", "безопасность деплоя", "наблюдаемость"],
    primarySkills: ["Kubernetes", "Terraform", "Prometheus", "GitHub Actions"],
    theoryFocus: ["SLO/SLA", "бюджеты ошибок", "паттерны отказоустойчивости"],
    practiceFocus: ["написать план rollout", "разобрать падающий деплой", "снизить MTTR"],
  },
  {
    id: "gameplay-engineer",
    title: "Разработчик игр (Gameplay)",
    category: "Game",
    description: "Игровая логика, оптимизация FPS, клиент-серверная синхронизация.",
    searchTerms: ["игры", "gameplay", "unity", "unreal", "графика"],
    focusAreas: ["игровой цикл", "оптимизация", "сетевая синхронизация"],
    primarySkills: ["C# / C++", "Unity / Unreal", "профилирование", "математика"],
    theoryFocus: ["игровая архитектура", "компенсация задержки", "бюджеты памяти"],
    practiceFocus: ["оптимизировать время кадра", "реализовать механику", "разобрать рассинхронизацию"],
  },
  {
    id: "cybersecurity-engineer",
    title: "Инженер по кибербезопасности",
    category: "Security",
    description: "Secure SDLC, threat modeling, обнаружение уязвимостей и hardening.",
    searchTerms: ["security", "кибербезопасность", "owasp", "угрозы", "тест на проникновение"],
    focusAreas: ["безопасность приложений", "обработка инцидентов", "снижение рисков"],
    primarySkills: ["OWASP", "SIEM", "IAM", "сетевая безопасность"],
    theoryFocus: ["моделирование угроз", "authn/authz", "эшелонированная защита"],
    practiceFocus: ["проверить уязвимый код", "предложить меры защиты", "составить план реагирования"],
  },
  {
    id: "systems-engineer",
    title: "Системный инженер",
    category: "Systems",
    description: "ОС, сети, low-level performance, многопоточность и диагностика.",
    searchTerms: ["systems", "linux", "kernel", "сеть", "многопоточность"],
    focusAreas: ["конкурентность", "память", "сетевое взаимодействие"],
    primarySkills: ["Linux", "C/C++", "профилирование", "TCP/IP"],
    theoryFocus: ["планирование", "модели памяти", "сетевые протоколы"],
    practiceFocus: ["разобрать deadlock", "оптимизировать путь syscalls", "диагностировать потерю пакетов"],
  },
  {
    id: "enterprise-architect",
    title: "Инженер enterprise-систем",
    category: "Enterprise",
    description: "Интеграции enterprise-систем, governance, поддержка legacy и миграции.",
    searchTerms: ["enterprise", "интеграция", "легаси", "архитектура", "soa"],
    focusAreas: ["интеграция", "миграция", "управление"],
    primarySkills: ["Java/.NET", "брокеры сообщений", "паттерны интеграции"],
    theoryFocus: ["ограниченные контексты", "управление", "управление изменениями"],
    practiceFocus: ["спроектировать план миграции", "выделить модуль из монолита", "определить контрактные тесты"],
  },
  {
    id: "fintech-platform",
    title: "Fintech-инженер",
    category: "Fintech",
    description: "Платежи, anti-fraud, соответствие требованиям, безопасность транзакций.",
    searchTerms: ["fintech", "платежи", "мошенничество", "риски", "соответствие требованиям"],
    focusAreas: ["надежность транзакций", "соответствие требованиям", "контроль рисков"],
    primarySkills: ["платежный API", "учетная книга", "правила рисков", "PCI DSS"],
    theoryFocus: ["согласованность в учетной книге", "предотвращение мошенничества", "аудируемость"],
    practiceFocus: ["спроектировать платежный поток", "обработать дублирующийся платеж", "разобрать неуспешный расчет"],
  },
  {
    id: "iot-platform",
    title: "IoT-инженер",
    category: "IoT",
    description: "Устройства, телеметрия, edge-компоненты, надежная доставка событий.",
    searchTerms: ["iot", "edge", "телеметрия", "mqtt", "прошивка", "устройства"],
    focusAreas: ["жизненный цикл устройства", "телеметрия", "надежность edge"],
    primarySkills: ["MQTT", "основы embedded", "временные ряды", "аутентификация устройств"],
    theoryFocus: ["компромиссы протоколов", "поведение офлайн", "безопасность на edge"],
    practiceFocus: ["спроектировать ingestion-пайплайн", "разобрать нестабильное устройство", "улучшить профиль расхода батареи"],
  },
  {
    id: "engineering-manager",
    title: "Руководитель разработки",
    category: "Management",
    description: "Люди, процессы, delivery, tech strategy и развитие команды.",
    searchTerms: ["management", "менеджер", "лид", "команда", "доставка"],
    focusAreas: ["лидерство в команде", "исполнение", "найм"],
    primarySkills: ["планирование", "1:1", "коммуникация со стейкхолдерами", "метрики"],
    theoryFocus: ["дизайн организации", "приоритизация", "коучинг"],
    practiceFocus: ["разрешить конфликт в команде", "провести postmortem инцидента", "собрать scorecard для найма"],
  },
];

export const VACANCY_BY_ID = new Map(VACANCY_OPTIONS.map((vacancy) => [vacancy.id, vacancy]));
