// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/interview/interview.proto
//
// NOTE: This is a placeholder stub. Run protoc to generate the real file.

package interviewpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

var _ InterviewServiceClient = (*interviewServiceClient)(nil)

// InterviewServiceClient is the client API for InterviewService.
type InterviewServiceClient interface {
	CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error)
	GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error)
	ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error)
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
}

type interviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterviewServiceClient(cc grpc.ClientConnInterface) InterviewServiceClient {
	return &interviewServiceClient{cc}
}

func (c *interviewServiceClient) CreateInterview(ctx context.Context, in *CreateInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error) {
	out := new(GetInterviewResponse)
	err := c.cc.Invoke(ctx, "/interview.InterviewService/CreateInterview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) GetInterview(ctx context.Context, in *GetInterviewRequest, opts ...grpc.CallOption) (*GetInterviewResponse, error) {
	out := new(GetInterviewResponse)
	err := c.cc.Invoke(ctx, "/interview.InterviewService/GetInterview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) ListInterviews(ctx context.Context, in *ListInterviewsRequest, opts ...grpc.CallOption) (*ListInterviewsResponse, error) {
	out := new(ListInterviewsResponse)
	err := c.cc.Invoke(ctx, "/interview.InterviewService/ListInterviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, "/interview.InterviewService/StartSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewServiceClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, "/interview.InterviewService/SubmitAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterviewServiceServer is the server API for InterviewService.
type InterviewServiceServer interface {
	CreateInterview(context.Context, *CreateInterviewRequest) (*GetInterviewResponse, error)
	GetInterview(context.Context, *GetInterviewRequest) (*GetInterviewResponse, error)
	ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error)
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	mustEmbedUnimplementedInterviewServiceServer()
}

type UnimplementedInterviewServiceServer struct{}

func (UnimplementedInterviewServiceServer) CreateInterview(context.Context, *CreateInterviewRequest) (*GetInterviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInterview not implemented")
}
func (UnimplementedInterviewServiceServer) GetInterview(context.Context, *GetInterviewRequest) (*GetInterviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterview not implemented")
}
func (UnimplementedInterviewServiceServer) ListInterviews(context.Context, *ListInterviewsRequest) (*ListInterviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInterviews not implemented")
}
func (UnimplementedInterviewServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedInterviewServiceServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedInterviewServiceServer) mustEmbedUnimplementedInterviewServiceServer() {}

func RegisterInterviewServiceServer(s grpc.ServiceRegistrar, srv InterviewServiceServer) {
	s.RegisterService(&InterviewService_ServiceDesc, srv)
}

var InterviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.InterviewService",
	HandlerType: (*InterviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateInterview", Handler: _InterviewService_CreateInterview_Handler},
		{MethodName: "GetInterview", Handler: _InterviewService_GetInterview_Handler},
		{MethodName: "ListInterviews", Handler: _InterviewService_ListInterviews_Handler},
		{MethodName: "StartSession", Handler: _InterviewService_StartSession_Handler},
		{MethodName: "SubmitAnswer", Handler: _InterviewService_SubmitAnswer_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interview/interview.proto",
}

func _InterviewService_CreateInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).CreateInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/interview.InterviewService/CreateInterview"}
	return interceptor(ctx, in, info, srv.(InterviewServiceServer).CreateInterview)
}

func _InterviewService_GetInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).GetInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/interview.InterviewService/GetInterview"}
	return interceptor(ctx, in, info, srv.(InterviewServiceServer).GetInterview)
}

func _InterviewService_ListInterviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).ListInterviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/interview.InterviewService/ListInterviews"}
	return interceptor(ctx, in, info, srv.(InterviewServiceServer).ListInterviews)
}

func _InterviewService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/interview.InterviewService/StartSession"}
	return interceptor(ctx, in, info, srv.(InterviewServiceServer).StartSession)
}

func _InterviewService_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServiceServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/interview.InterviewService/SubmitAnswer"}
	return interceptor(ctx, in, info, srv.(InterviewServiceServer).SubmitAnswer)
}
