// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/scoring/scoring.proto
//
// NOTE: This is a placeholder stub. Run protoc to generate the real file.

package scoringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

var _ ScoringServiceClient = (*scoringServiceClient)(nil)

// ScoringServiceClient is the client API for ScoringService.
type ScoringServiceClient interface {
	ScoreAnswer(ctx context.Context, in *ScoringRequest, opts ...grpc.CallOption) (*ScoringResponse, error)
	GetEvaluation(ctx context.Context, in *GetEvaluationRequest, opts ...grpc.CallOption) (*GetEvaluationResponse, error)
	ListEvaluations(ctx context.Context, in *ListEvaluationsRequest, opts ...grpc.CallOption) (*ListEvaluationsResponse, error)
}

type scoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoringServiceClient(cc grpc.ClientConnInterface) ScoringServiceClient {
	return &scoringServiceClient{cc}
}

func (c *scoringServiceClient) ScoreAnswer(ctx context.Context, in *ScoringRequest, opts ...grpc.CallOption) (*ScoringResponse, error) {
	out := new(ScoringResponse)
	err := c.cc.Invoke(ctx, "/scoring.ScoringService/ScoreAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetEvaluation(ctx context.Context, in *GetEvaluationRequest, opts ...grpc.CallOption) (*GetEvaluationResponse, error) {
	out := new(GetEvaluationResponse)
	err := c.cc.Invoke(ctx, "/scoring.ScoringService/GetEvaluation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) ListEvaluations(ctx context.Context, in *ListEvaluationsRequest, opts ...grpc.CallOption) (*ListEvaluationsResponse, error) {
	out := new(ListEvaluationsResponse)
	err := c.cc.Invoke(ctx, "/scoring.ScoringService/ListEvaluations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoringServiceServer is the server API for ScoringService.
type ScoringServiceServer interface {
	ScoreAnswer(context.Context, *ScoringRequest) (*ScoringResponse, error)
	GetEvaluation(context.Context, *GetEvaluationRequest) (*GetEvaluationResponse, error)
	ListEvaluations(context.Context, *ListEvaluationsRequest) (*ListEvaluationsResponse, error)
	mustEmbedUnimplementedScoringServiceServer()
}

type UnimplementedScoringServiceServer struct{}

func (UnimplementedScoringServiceServer) ScoreAnswer(context.Context, *ScoringRequest) (*ScoringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreAnswer not implemented")
}
func (UnimplementedScoringServiceServer) GetEvaluation(context.Context, *GetEvaluationRequest) (*GetEvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvaluation not implemented")
}
func (UnimplementedScoringServiceServer) ListEvaluations(context.Context, *ListEvaluationsRequest) (*ListEvaluationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvaluations not implemented")
}
func (UnimplementedScoringServiceServer) mustEmbedUnimplementedScoringServiceServer() {}

func RegisterScoringServiceServer(s grpc.ServiceRegistrar, srv ScoringServiceServer) {
	s.RegisterService(&ScoringService_ServiceDesc, srv)
}

var ScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scoring.ScoringService",
	HandlerType: (*ScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ScoreAnswer", Handler: _ScoringService_ScoreAnswer_Handler},
		{MethodName: "GetEvaluation", Handler: _ScoringService_GetEvaluation_Handler},
		{MethodName: "ListEvaluations", Handler: _ScoringService_ListEvaluations_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scoring/scoring.proto",
}

func _ScoringService_ScoreAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).ScoreAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/scoring.ScoringService/ScoreAnswer"}
	return interceptor(ctx, in, info, srv.(ScoringServiceServer).ScoreAnswer)
}

func _ScoringService_GetEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/scoring.ScoringService/GetEvaluation"}
	return interceptor(ctx, in, info, srv.(ScoringServiceServer).GetEvaluation)
}

func _ScoringService_ListEvaluations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEvaluationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).ListEvaluations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/scoring.ScoringService/ListEvaluations"}
	return interceptor(ctx, in, info, srv.(ScoringServiceServer).ListEvaluations)
}
