apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: report-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8086"
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: report-service
