apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: resume-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: resume-service
