apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8087"
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: notification-service
