apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: real-ass
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: user-service
